"""create recovery_cases table

Revision ID: 51974c14c187
Revises: 
Create Date: 2026-06-03 09:48:57.656567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51974c14c187'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recovery_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_name', sa.String(length=255), nullable=False),
    sa.Column('disaster_type', sa.String(length=64), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('incident_date', sa.Date(), nullable=False),
    sa.Column('insurance_provider', sa.String(length=255), nullable=True),
    sa.Column('insurance_policy_number', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recovery_cases')
    # ### end Alembic commands ###
